customer/urls.py
from django.urls import path

from . import views

app_name = 'customer'
urlpatterns = [
    path('<str:url_city_name>/', views.city_layout, name='city_layout'),
    path('<str:url_city_name>/<str:url_mall_name>/', views.mall_restaurants, name='mall_restaurants'),
    path('<str:url_city_name>/<str:url_mall_name>/<str:url_rest_name>/', views.restaurant_menu, name='restaurant_menu'),
    path('<str:url_city_name>/<str:url_mall_name>/<str:url_rest_name>/order/', views.order, name='order'),
]

food_me_backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('customer/', include('customer.urls')),
    #path('restaurant/', include('restaurant.urls')),
    path('admin/', admin.site.urls),
]

customer/models.py
from django.db import models
from datetime import datetime

# Create your models here.


class City(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class ShoppingMall(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def set_name(self, name):
        self.name = name

    def set_address(self, address):
        self.address = address


class Restaurant(models.Model):
    mall = models.ForeignKey(ShoppingMall, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def set_name(self, name):
        self.name = name


class Menu(models.Model):
    restaurant = models.OneToOneField(Restaurant, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return "%s menu" % self.restaurant.name


class MenuEntry(models.Model):
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    calories = models.CharField(max_length=10)
    price = models.FloatField(default=1)

    def set_name(self, name):
        self.name = name

    def set_calories(self, calories):
        self.calories = str(calories)

    def set_price(self, price):
        self.price = str(price)

    def __str__(self):
        return self.name


class User(models.Model):
    mobile = models.CharField(max_length=20)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    def __str__(self):
        return self.first_name + " " + self.last_name

    def set_first_name(self, first_name):
        self.first_name = first_name

    def set_second_name(self, second_name):
        self.second_name = second_name


class Order(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    menu_entries = models.ManyToManyField(MenuEntry)
    time_of_order = models.DateTimeField(default=datetime.now, blank=True)

    def get_menu_entries(self):
        return self.menu_entries

    def get_total(self):
        return sum([entry.price for entry in self.menu_entries.all()])

    def __str__(self):
        return self.owner.first_name + self.time_of_order


class Cart(models.Model):
    pass

restaurant/models.py
from django.db import models

# Create your models here.

customer/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse

import json
from .models import *

# Create your views here.


def city_layout(request, url_city_name):
    city_name = url_city_name.replace('+', ' ')
    city = City.objects.filter(name=city_name)[0]
    malls = city.shoppingmall_set.all()
    mall_names, mall_addresses = [], []
    for mall in malls:
        mall_names.append(mall.name)

    for mall in malls:
        mall_addresses.append(mall.address)

    mall_dictionary = [{"Name": t, "Address": s} for t, s in zip(mall_names, mall_addresses)]
    return JsonResponse(json.dumps(mall_dictionary), safe=False)


def mall_restaurants(request, url_city_name, url_mall_name):
    mall_name = url_mall_name.replace('+', ' ')
    city_name = url_city_name.replace('+', ' ')
    city = City.objects.filter(name=city_name)[0]
    mall = city.shoppingmall_set.filter(name=mall_name)[0]
    restaurants = mall.restaurant_set.all()
    context = {
        'restaurants': restaurants,
        'mall_name': url_mall_name,
        'city_name': url_city_name
    }

    return render(request, 'customer/mall_restaurants.html', context)


def restaurant_menu(request, url_city_name, url_mall_name, url_rest_name):
    mall_name = url_mall_name.replace('+', ' ')
    city_name = url_city_name.replace('+', ' ')
    rest_name = url_rest_name.replace('+', ' ')
    city = City.objects.filter(name=city_name)[0]
    mall = city.shoppingmall_set.filter(name=mall_name)[0]
    restaurant = mall.restaurant_set.filter(name=rest_name)[0]
    menu_entry_set = restaurant.menu.menuentry_set.all()
    context = {
        'entry_set': menu_entry_set,
        'city': url_city_name,
        'mall': url_mall_name,
        'restaurant': url_rest_name,
    }

    return render(request, 'customer/restaurant_menu.html', context)


def order(request, url_city_name, url_mall_name, url_rest_name):
    mall_name = url_mall_name.replace('+', ' ')
    city_name = url_city_name.replace('+', ' ')
    rest_name = url_rest_name.replace('+', ' ')
    city = City.objects.filter(name=city_name)[0]
    mall = city.shoppingmall_set.filter(name=mall_name)[0]
    restaurant = mall.restaurant_set.filter(name=rest_name)[0]
    menu_entry_set = restaurant.menu.menuentry_set.all()
    print(request.POST)
    received_entries = request.POST.getlist('dish-name')
    print(received_entries)
    for entry in received_entries:
        if menu_entry_set.filter(name=entry).exists():
            continue
        else:
            context = {
                'entry_set': received_entries,
                'error_message': 'unknown item',
                'faulty_entry': entry
            }
            return render(request, 'customer/cart.html', context)

    context = {
        'entry_set': received_entries,
        'city': url_city_name,
        'mall': url_mall_name,
        'rest': url_rest_name
    }
    return render(request, 'customer/cart.html', context)

restaurant/views.py
from django.shortcuts import render

# Create your views here.

customer/templates/customer/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if error_message %}
<p><strong>{{ error_message }} {{ faulty_item }}</strong></p>
{% else %}
<form id="shopping-cart" action="cart.html" method="post">
    <table class="shopping-cart">
        <thead>
        <tr>
            <th scope="col">Item</th>
            <th scope="col">Qty</th>
            <th scope="col">Price</th>
        </tr>
        </thead>
        <tbody></tbody>
    </table>
    <p id="sub-total">
        <strong>Sub Total</strong>: <span id="stotal"></span>
    </p>
    <ul id="shopping-cart-actions">
        <li>
            <input type="submit" name="update" id="update-cart" class="btn" value="Update Cart"/>
        </li>
        <li>
            <input type="submit" name="delete" id="empty-cart" class="btn" value="Empty Cart"/>
        </li>
        <li>
            <a href="{% url 'customer:restaurant_menu' city mall rest %}" class="btn">Continue Shopping</a>
        </li>
        <li>
            <a href="checkout.html" class="btn">Go To Checkout</a>
        </li>
        <li>
            <a href="{% url 'customer:mall_restaurants' city mall %}" class="btn">Choose another restaurant</a>
        </li>
    </ul>
</form>

</body>
{% endif %}
</html>

customer/templates/customer/city_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

customer/templates/customer/mall_restaurants.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if restaurants %}
    <ul>
    {% for rest in restaurants %}
        <li><a href="{% url 'customer:restaurant_menu' city_name mall_name rest.name %}">{{ rest.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
<p>No restaurants in our db yet</p>
{% endif %}
</body>
</html>

customer/templates/customer/restaurant_menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% if entry_set %}
    {% for menu_entry in entry_set %}
    <div class="product-description" data-name="{{ menu_entry.name }}" data-price="5">
        <h3 class="product-name">{{ menu_entry.name }}</h3>
            <p class="product-price">{{ menu_entry.price }} ru</p>
            <p>Calories {{ menu_entry.calories }} </p>
            <form class="add-to-cart" action="{% url 'customer:order' city mall restaurant %}" method="post">
            {% csrf_token %}
                <div>
{#                    <label for="qty-1">Quantity</label>#}
                    <input type="text" placeholder="Quantity" name="item" id="qty-1" class="qty" />
                    <input type="text" name="dish-name" value="{{ menu_entry.name }}" style="visibility: hidden"/>
                </div>
                <p><input type="submit" value="Add to cart" class="btn" /></p>
            </form>
    </div>
    {% endfor %}
{% else %}
<p>There is no completed menu for this restaurant yet.</p>
{% endif %}

</body>
</html>